In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [15]:
b= np.array([1,23,45,56,89,75,25,36,98,74,4,13,15,10,14,12,2,23])
b.shape

(18,)

In [18]:
np.argsort(b) # give the indexes of array sorting

array([ 0, 16, 10, 13, 15, 11, 14, 12, 17,  1,  6,  7,  2,  3,  9,  5,  4,
        8], dtype=int64)

In [19]:
np.argmin(b)

0

In [20]:
np.argmax(b)

8

In [21]:
b=b.reshape(6,3)

In [26]:
np.argsort(b, axis=0)# by default it take axis=1

array([[0, 5, 3],
       [5, 3, 4],
       [4, 4, 5],
       [2, 0, 0],
       [1, 2, 1],
       [3, 1, 2]], dtype=int64)

In [27]:
np.argmin(b)

0

In [28]:
np.argmax(b)

8