## Basic function

In [1]:
import numpy as np
A = np.array([[3,2,5.2,7,0],[1,12,3,5,4]], dtype='int32') # int32 will force dtype to be integer 32
print(A)

[[ 3  2  5  7  0]
 [ 1 12  3  5  4]]


In [2]:
A.shape

(2, 5)

In [3]:
A.dtype

dtype('int32')

In [4]:
np.zeros((4,6)) # it will assign zero values 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones(9).dtype

dtype('float64')

In [6]:
np.empty((4,6)) # it will give empty location in memory

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
A

array([[ 3,  2,  5,  7,  0],
       [ 1, 12,  3,  5,  4]])

In [7]:
A*A

array([[  9,   4,  25,  49,   0],
       [  1, 144,   9,  25,  16]])

In [8]:
A+A

array([[ 6,  4, 10, 14,  0],
       [ 2, 24,  6, 10,  8]])

In [10]:
A/A

C:\Users\Laptop\AppData\Local\Temp/ipykernel_556/3735796488.py:1: RuntimeWarning: invalid value encountered in true_divide
  A/A


array([[ 1.,  1.,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
A**A

array([[        27,          4,       3125,     823543,          1],
       [         1, -251658240,         27,       3125,        256]],
      dtype=int32)

In [12]:
np.array([24**24], dtype='int32')

OverflowError: Python int too large to convert to C long

In [13]:
1/A

C:\Users\Laptop\AppData\Local\Temp/ipykernel_556/2033393754.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/A


array([[0.33333333, 0.5       , 0.2       , 0.14285714,        inf],
       [1.        , 0.08333333, 0.33333333, 0.2       , 0.25      ]])

## Slicing

In [14]:
B= np.array([5,4,64,3,3,3])
C= B[4:6]

In [16]:
C

array([3, 3])

In [17]:
C[0]=9

In [18]:
B

array([ 5,  4, 64,  3,  9,  3])

In [19]:
D=  np.array([5,4,64,3,3,3])
E=D[4:6].copy()
E[0]= 9

In [20]:
D

array([ 5,  4, 64,  3,  3,  3])

In [21]:
A[0,3]

7